version: '3'

services:
  userDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3309:3306
  shopDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3310:3306
  adminer:
    image: adminer
    ports:
      - 8081:8080
  redis:
    image: redis
    ports:
      - 6379:6379